<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalFinTracker.Application\PersonalFinTracker.Application.csproj" />
    <ProjectReference Include="..\PersonalFinTracker.Domain\PersonalFinTracker.Domain.csproj" />
  </ItemGroup>

</Project>
